#!/usr/bin/env python3
"""Generate the resource pages added from 1.38.0 on.

Why a generator
---------------
The first seven resource pages were hand-written, and each carried its own copy
of the same 71 line stylesheet. Two had already drifted apart by the time the
audit found them, which is what produced docs/resources.css in 1.37.0. The
shell of one of these pages -- the head, the CSP, the crumbs, the checked
stamp, the read-next box, the limits section -- is the same shape every time,
so it lives here rather than being pasted an eighth time.

The bar and the footer are not here. Those come from site_chrome.py, written in
by build_chrome.py, same as every other page.

The rule these pages follow, unchanged from the shelf they join
--------------------------------------------------------------
This site organizes the question. The institution keeps the answer. Every fact
attributed to an agency was read on that agency's own page on the date in
CHECKED, and the page says so. Where a figure varies by policy, by carrier or
by state, this says that it varies and sends the reader to the document that
decides -- it does not print a number that would be wrong for most readers.

Adding a page: add an entry to PAGES, add it to RESOURCES in site_chrome.py, a
row on docs/resources/index.html, a RESOURCE_CHECKED entry in build_chrome.py,
and a sitemap entry. Then run this and build_chrome.py.
"""

import io
import json
import os

import site_chrome

OUT = os.path.join("docs", "resources")
CHECKED = "22 August 2026"
ISO = "2026-08-22"

SHELL = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Generated by build_resource_pages.py. Edit it there, not here. Every
     institutional fact below was read on the named source's own page on the
     date in the checked line. Change a fact, re-read the source, move the
     date. -->
<title>{title}</title>
<meta name="description" content="{description}">
<meta property="og:title" content="{og_title}">
<meta property="og:description" content="{og_description}">
<meta property="og:type" content="article">
<meta property="og:url" content="https://gulfcoasthomemaintenance.com/resources/{slug}/">
<meta property="og:site_name" content="Gulf Coast Home Maintenance">
<meta property="og:image" content="https://gulfcoasthomemaintenance.com/img/hero-1600.jpg">
<meta property="og:image:width" content="1600">
<meta property="og:image:height" content="1200">
<meta property="og:image:alt" content="A live oak hung with Spanish moss over the roof of a Gulf Coast house at sunset.">
<meta name="twitter:card" content="summary_large_image">
<meta name="theme-color" content="#17322c">
<link rel="canonical" href="https://gulfcoasthomemaintenance.com/resources/{slug}/">

<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.google-analytics.com https://*.googletagmanager.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com; form-action 'none'; frame-src 'none'; base-uri 'none'; object-src 'none'">
<meta name="referrer" content="strict-origin-when-cross-origin">

<script src="../../analytics.js"></script>

<link rel="icon" href="../../favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="../../icon-180.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Newsreader:opsz,wght@6..72,400;6..72,600;6..72,700&display=swap">
<link rel="stylesheet" href="../../theme.css">
<link rel="stylesheet" href="../../nav.css">
<link rel="stylesheet" href="../../resources.css">

<script type="application/ld+json">
{structured}
</script>
</head>
<body>

<div class="topbar"></div>

<header>
  <div class="wrap">
    <p class="crumbs">
      <a href="../../">Home</a><span class="sep">/</span><a href="../">Grants and programs</a>
    </p>
    <h1>{h1}</h1>
    <p>{standfirst}</p>
  </div>
</header>

<main>
  <div class="wrap">
    <p class="checked">{checked}</p>

{body}

    <div class="next">
      <span class="label">Read next</span>
      <ul>
{next_rows}
      </ul>
    </div>

    <h2>What this page is not</h2>
    <p>{limits}</p>
  </div>
</main>

<footer></footer>

</body>
</html>
"""


def article_ld(page):
    return json.dumps({
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "Article",
                "headline": page["og_title"],
                "description": page["og_description"],
                "datePublished": ISO,
                "dateModified": ISO,
                "author": {"@type": "Organization",
                           "name": "Gulf Coast Home Maintenance",
                           "url": "https://gulfcoasthomemaintenance.com/"},
                "mainEntityOfPage":
                    "https://gulfcoasthomemaintenance.com/resources/%s/" % page["slug"],
            },
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1,
                     "name": "Gulf Coast Home Maintenance",
                     "item": "https://gulfcoasthomemaintenance.com/"},
                    {"@type": "ListItem", "position": 2, "name": "Grants and programs",
                     "item": "https://gulfcoasthomemaintenance.com/resources/"},
                    {"@type": "ListItem", "position": 3, "name": page["h1"]},
                ],
            },
        ],
    }, indent=2, ensure_ascii=False)


def render(page):
    rows = "\n".join(
        '        <li><a href="{0}">{1}</a>\n          <span class="what">&middot; {2}</span></li>'
        .format(href, label, what) for href, label, what in page["next"])
    return SHELL.format(structured=article_ld(page), next_rows=rows, **page)


def main():
    from resource_content import PAGES
    for page in PAGES:
        folder = os.path.join(OUT, page["slug"])
        os.makedirs(folder, exist_ok=True)
        path = os.path.join(folder, "index.html")
        io.open(path, "w", encoding="utf-8", newline="\n").write(render(page))
        print("  %s" % path)
    print("%d resource pages generated" % len(PAGES))
    print("Now run build_chrome.py so they get the bar and the footer.")


if __name__ == "__main__":
    main()
